name: Build

permissions:
  id-token: write
  pages: write

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      previous-version: ${{ steps.previous-version.outputs.PREVIOUS_VERSION }}
      current-version: ${{ steps.current-version.outputs.CURRENT_VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - id: previous-version
        run: |
          PREVIOUS_VERSION=$(git show HEAD~1:projects/lendai-us/design-system/package.json | jq -r '.version')
          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> "$GITHUB_OUTPUT"

      - id: current-version
        run: |
          CURRENT_VERSION=$(jq -r '.version' projects/lendai-us/design-system/package.json)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs:
      - version

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run ng build @lendai-us/cdk

      - run: npm run ng build @lendai-us/design-system

      - run: npm run build-storybook

      - uses: actions/upload-pages-artifact@v2
        if: ${{ needs.version.outputs.previous-version != needs.version.outputs.current-version && github.ref == 'refs/heads/main' }}
        with:
          path: storybook-static

      - uses: actions/upload-artifact@v4
        if: ${{ needs.version.outputs.previous-version != needs.version.outputs.current-version && github.ref == 'refs/heads/main' }}
        with:
          name: design-system
          path: dist/lendai-us/design-system

  deploy:
    runs-on: ubuntu-latest
    if: ${{ needs.version.outputs.previous-version != needs.version.outputs.current-version && github.ref == 'refs/heads/main' }}
    needs:
      - version
      - build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - uses: actions/download-artifact@v4
        with:
          name: design-system
          path: dist/lendai-us/design-system

      - id: publish
        run: |
          npm run publish:design-system
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
